/**
 * useAddSupperTake — add the caller's own take to a Supper (TICKET-082, Phase 3).
 *
 * Each take is the author's OWN `entries` row, bound to the supper by supper_id.
 * The `add-take` action (branched server-side on body.supper_id) validates the
 * caller is a supper member, creates their entry, and returns the take row with
 * supper_id nested in `data`.
 *
 * Canonical mutation lifecycle (lib/mutations.md):
 *   onMutate  → cancel + snapshot the supper-detail cache, optimistically push
 *               (or replace) the caller's take so the merged screen updates
 *               instantly; return the snapshot for rollback.
 *   onError   → restore the snapshot.
 *   onSuccess → refresh the caller's profile / Spots / Taste aggregates,
 *               which all derive from the newly-created entry.
 *   onSettled → narrow-invalidate queryKeys.suppers.detail(supperId). The server
 *               take carries joined display_name/avatar_url + a real entry_id +
 *               server-sorted entry_photos that the optimistic stub can't
 *               faithfully synthesise, so a refetch reconciles (this is a
 *               "when invalidation IS appropriate" case).
 *
 * NOTE on warnings: the server's `duplicate_submission` warning is a SIBLING of
 * `data` and is stripped by callEdgeFn (Phase-2 review NIT). We do not depend on
 * it here; client_nonce dedup makes a retried take return the existing row.
 */
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { callEdgeFn } from '@/lib/edgeInvoke';
import { queryKeys } from '@/lib/queryKeys';
import { useAuth } from '@/providers/AuthProvider';
import { safeRandomUUID } from '@/lib/uuid';
import { invalidateEntryTasteCaches } from '@/hooks/entries/invalidateEntryTaste';
import type { SupperDetail, SupperTake } from './useSupper';

export interface AddSupperTakeInput {
    supper_id: string;
    rating: number | null;
    content?: string | null;
    dish_description?: string | null;
    /** When the caller ate (ISO). Defaults server-side to now when omitted. */
    visited_at?: string | null;
    photo_urls?: string[];
    vibe_rating?: number | null;
    flavor_rating?: number | null;
    service_rating?: number | null;
    value_rating?: number | null;
    liked?: boolean;
    /** Generated by the hook — do not pass from callers. */
    client_nonce?: string;
}

/** Server take row (entries row with supper_id) returned by add-take. */
interface ServerTakeRow {
    id?: string;
    user_id?: string;
    restaurant_id?: string | null;
    supper_id: string;
    rating?: number | null;
    content?: string | null;
    dish_description?: string | null;
    visited_at?: string | null;
    created_at?: string;
    vibe_rating?: number | null;
    flavor_rating?: number | null;
    service_rating?: number | null;
    value_rating?: number | null;
    liked?: boolean | null;
    photo_url?: string | null;
}

async function addSupperTake(input: AddSupperTakeInput): Promise<ServerTakeRow> {
    return callEdgeFn<ServerTakeRow>('entry', {
        action: 'add-take',
        body: {
            supper_id: input.supper_id,
            rating: input.rating,
            content: input.content ?? null,
            dish_description: input.dish_description ?? null,
            visited_at: input.visited_at ?? null,
            photo_urls: input.photo_urls ?? [],
            vibe_rating: input.vibe_rating ?? null,
            flavor_rating: input.flavor_rating ?? null,
            service_rating: input.service_rating ?? null,
            value_rating: input.value_rating ?? null,
            liked: input.liked ?? false,
            client_nonce: input.client_nonce,
        },
    });
}

interface MutationContext {
    previous?: SupperDetail;
    nonce: string;
}

export function useAddSupperTake() {
    const qc = useQueryClient();
    const { user } = useAuth();
    const viewerId = user?.id ?? '';

    return useMutation<ServerTakeRow, Error, AddSupperTakeInput, MutationContext>({
        mutationFn: (input) => {
            const client_nonce = input.client_nonce ?? safeRandomUUID();
            return addSupperTake({ ...input, client_nonce });
        },

        onMutate: async (input): Promise<MutationContext> => {
            const nonce = input.client_nonce ?? safeRandomUUID();
            input.client_nonce = nonce;

            const key = queryKeys.suppers.detail(input.supper_id);
            await qc.cancelQueries({ queryKey: key });
            const previous = qc.getQueryData<SupperDetail>(key);

            if (previous && viewerId) {
                const roster = previous.roster.find((r) => r.user_id === viewerId);
                const now = new Date().toISOString();
                const optimisticTake: SupperTake = {
                    entry_id: `optimistic-${nonce}`,
                    user_id: viewerId,
                    restaurant_id: previous.supper.restaurant_id,
                    supper_id: input.supper_id,
                    rating: input.rating ?? null,
                    content: input.content ?? null,
                    dish_description: input.dish_description ?? null,
                    visited_at: input.visited_at ?? now,
                    created_at: now,
                    vibe_rating: input.vibe_rating ?? null,
                    flavor_rating: input.flavor_rating ?? null,
                    service_rating: input.service_rating ?? null,
                    value_rating: input.value_rating ?? null,
                    liked: input.liked ?? false,
                    photo_url: input.photo_urls?.[0] ?? null,
                    photos: input.photo_urls ?? [],
                    display_name: roster?.display_name ?? null,
                    avatar_url: roster?.avatar_url ?? null,
                };
                // Replace any existing take by this viewer, else append.
                const existingIdx = previous.takes.findIndex((t) => t.user_id === viewerId);
                const nextTakes =
                    existingIdx >= 0
                        ? previous.takes.map((t, i) => (i === existingIdx ? optimisticTake : t))
                        : [...previous.takes, optimisticTake];
                qc.setQueryData<SupperDetail>(key, { ...previous, takes: nextTakes });
            }

            return { previous, nonce };
        },

        onError: (_err, input, ctx) => {
            if (ctx?.previous !== undefined) {
                qc.setQueryData(queryKeys.suppers.detail(input.supper_id), ctx.previous);
            }
        },

        onSuccess: (data) => {
            // A Supper take is an entries row owned by the caller. Refresh every
            // profile/Taste aggregate that derives from it, using the canonical
            // owner returned by the server when available.
            const ownerId = data.user_id ?? viewerId;
            if (ownerId) invalidateEntryTasteCaches(qc, ownerId);
        },

        onSettled: (_data, _err, input) => {
            // Narrow refetch: the server take carries joined display data, the real
            // entry_id, and server-sorted photos the optimistic stub can't synthesise.
            qc.invalidateQueries({ queryKey: queryKeys.suppers.detail(input.supper_id) });
            // Supper v2: the take also flips the feed SupperCard (viewer_filled /
            // filled_count / seats) and dismisses the in-app nudge — both derived from
            // the table-activity cache. viewer_filled etc. are server-shape the optimistic
            // stub can't synthesise, so refetch the feed. activityAll() (the ['tableActivity']
            // prefix) catches every table + filter variant; we don't carry table_id here.
            qc.invalidateQueries({ queryKey: queryKeys.tables.activityAll() });
        },
    });
}
