/**
 * Hook to create a meal log entry.
 * Calls the entry edge function which handles restaurant upsert,
 * table sharing, and user_restaurant_status updates.
 *
 * TICKET-037 (P2-13): reads optional `warnings` from response and surfaces
 * a toast when companion tagging partially fails.
 *
 * TICKET-036 (P0-6): generates a `client_nonce` (uuid) per submission.
 *   - Server uses it to dedupe retries (entries_user_client_nonce_uidx).
 *   - Client uses it to optimistically prepend a placeholder row to the
 *     viewer's mySolo cache so the Journal tab doesn't flash empty
 *     during the round-trip, then swaps the placeholder for the real
 *     row in onSuccess. onError rolls back from snapshot.
 */
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/lib/supabase';
import { queryKeys } from '@/lib/queryKeys';
import { useToast } from '@/providers/ToastProvider';
import type { SoloShareActivity } from '@/hooks/tables/useTableActivity';

export interface CreateEntryInput {
    restaurant?: {
        external_id: string;
        name: string;
        location?: {
            address?: string;
            locality?: string;
            country?: string;
        };
        types?: string[];
        latitude?: number;
        longitude?: number;
        photoReference?: string;
    };
    rating?: number | null;
    content?: string;
    dish_description?: string;
    cooked_by?: string;
    visited_at?: string;
    table_id?: string;
    visibility?: 'private' | 'friends' | 'table' | 'both';
    participant_ids?: string[];
    /** Companion tagging — who was there (distinct from Round participant_ids) */
    companion_ids?: string[];
    vibe_rating?: number | null;
    flavor_rating?: number | null;
    service_rating?: number | null;
    value_rating?: number | null;
    photo_url?: string;
    photo_urls?: string[];
    /** Generated by useCreateEntry — do not pass from callers. */
    client_nonce?: string;
}

async function createEntry(input: CreateEntryInput): Promise<any> {
    // The entry edge function returns { data: EntryRow, warnings?: [...] }.
    // callEdgeFn returns whatever's at `data.data` — we lose `warnings`.
    // Fall back to direct invoke for this one call so we can read the warnings
    // envelope. (Acceptable exception to the callEdgeFn doctrine — documented
    // here, and warnings is a TICKET-037 P2-13 quirk that the helper API
    // doesn't yet expose. If a third hook needs envelope access we'll
    // generalize callEdgeFn to return { data, meta }.)
    const { data: { session } } = await supabase.auth.getSession();
    const { data, error } = await supabase.functions.invoke('entry', {
        body: input,
        headers: session?.access_token
            ? { Authorization: `Bearer ${session.access_token}` }
            : undefined,
    });
    if (error) throw error;
    if (data?.error) throw new Error(data.error);
    const entryRow = data?.data ?? {};
    if (data?.warnings) {
        (entryRow as any).__warnings = data.warnings;
    }
    return entryRow;
}

/**
 * Build a placeholder SoloShareActivity from the user's input so we can
 * optimistically prepend it to the mySolo cache. The id is `optimistic-<nonce>`
 * so onSuccess can find + swap it for the real server row.
 */
function buildOptimisticSoloShare(
    input: CreateEntryInput,
    userId: string,
    nonce: string,
): SoloShareActivity {
    const now = new Date().toISOString();
    const visited = input.visited_at ?? now;
    return {
        type: 'solo_share',
        id: `optimistic-${nonce}`,
        user_id: userId,
        restaurant_id: null,
        rating: input.rating ?? null,
        content: input.content ?? null,
        dish_description: input.dish_description ?? null,
        visited_at: visited,
        created_at: now,
        sort_date: visited,
        photo_url: input.photo_urls?.[0] ?? input.photo_url ?? null,
        photo_count: input.photo_urls?.length ?? (input.photo_url ? 1 : 0),
        reaction_count: 0,
        comment_count: 0,
        top_emojis: [],
        my_reactions: [],
        restaurants: input.restaurant
            ? {
                  id: '',
                  name: input.restaurant.name,
                  address: input.restaurant.location?.address ?? null,
                  city: input.restaurant.location?.locality ?? null,
                  photo_url: null,
              }
            : null,
        profiles: { display_name: '' },
    };
}

export function useCreateEntry(userId?: string | null, tableId?: string | null) {
    const qc = useQueryClient();
    const toast = useToast();

    return useMutation({
        mutationFn: (input: CreateEntryInput) => {
            // Generate the nonce here so the same value flows through both the
            // server call (server stores it for dedupe) and the optimistic row.
            const client_nonce = input.client_nonce ?? (globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`);
            return createEntry({ ...input, client_nonce });
        },

        onMutate: async (input) => {
            if (!userId) return undefined;
            const nonce = input.client_nonce ?? (globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`);
            // Stash the nonce on the input so mutationFn uses the same value.
            input.client_nonce = nonce;

            const mySoloKey = queryKeys.entries.mySolo(userId);
            await qc.cancelQueries({ queryKey: mySoloKey });
            const previousMySolo = qc.getQueryData<SoloShareActivity[]>(mySoloKey);

            // Only prepend if this entry would be visible on mySolo
            // (table_id null + table_night_id null). For Round/Table-shared
            // entries the row lives on tables.activity, not mySolo.
            if (!input.table_id) {
                const optimisticRow = buildOptimisticSoloShare(input, userId, nonce);
                qc.setQueryData<SoloShareActivity[]>(mySoloKey, (prev) =>
                    prev ? [optimisticRow, ...prev] : [optimisticRow],
                );
            }

            return { previousMySolo, mySoloKey, nonce };
        },

        onError: (_err, _input, context) => {
            if (context?.mySoloKey && context.previousMySolo !== undefined) {
                qc.setQueryData(context.mySoloKey, context.previousMySolo);
            }
        },

        onSuccess: (result, _input, context) => {
            // Surface companion tag failures as a non-blocking toast (TICKET-037 P2-13)
            const warnings: Array<{ type: string }> | undefined = (result as any)?.__warnings;
            if (warnings?.some((w) => w.type === 'companion_tag_failed')) {
                toast.show("Couldn't tag some friends.");
            }

            if (userId && context?.mySoloKey && context.nonce) {
                // P0-6: swap the optimistic row for the real one (matched by
                // nonce → optimistic-<nonce>) so cache holds the server id +
                // restaurant_id without a refetch.
                const optimisticId = `optimistic-${context.nonce}`;
                qc.setQueryData<SoloShareActivity[]>(context.mySoloKey, (prev) => {
                    if (!prev) return prev;
                    return prev.map((row) =>
                        row.id === optimisticId
                            ? {
                                  ...row,
                                  id: result?.id ?? row.id,
                                  restaurant_id: result?.restaurant_id ?? row.restaurant_id,
                                  // restaurants join data isn't on the bare insert
                                  // response; rely on next-focus refetch for it.
                              }
                            : row,
                    );
                });
            }

            // Caches we don't yet prepend to: feed.all / atlas.index /
            // entriesForDayAll have aggregate fields (trending, city stats,
            // day buckets) that are too risky to patch locally without a
            // full server-shape replica. Narrow invalidate keeps them
            // accurate. When we move them to optimistic-prepend we can drop
            // these too. (P0-6 follow-up.)
            if (userId) {
                qc.invalidateQueries({ queryKey: queryKeys.entries.forDayAll(userId) });
                qc.invalidateQueries({ queryKey: queryKeys.feed.all(userId) });
            }
            if (tableId) {
                qc.invalidateQueries({ queryKey: queryKeys.tables.activity(tableId) });
                qc.invalidateQueries({ queryKey: queryKeys.atlas.index(tableId) });
            }
        },
    });
}

