/** Curated home-city options. Free text remains valid wherever this list is used. */
export const CITIES = [
    'Aalborg, Denmark',
    'Aarhus, Denmark',
    'Abidjan, Ivory Coast',
    'Abu Dhabi, United Arab Emirates',
    'Abuja, Nigeria',
    'Acapulco, Mexico',
    'Accra, Ghana',
    'Addis Ababa, Ethiopia',
    'Adelaide, Australia',
    'Agadir, Morocco',
    'Agra, India',
    'Ahmedabad, India',
    'Aix-en-Provence, France',
    'Albuquerque, United States',
    'Alexandria, Egypt',
    'Algiers, Algeria',
    'Alicante, Spain',
    'Almaty, Kazakhstan',
    'Amman, Jordan',
    'Amritsar, India',
    'Amsterdam, Netherlands',
    'Ankara, Turkey',
    'Annecy, France',
    'Antalya, Turkey',
    'Antananarivo, Madagascar',
    'Antigua Guatemala, Guatemala',
    'Antwerp, Belgium',
    'Apia, Samoa',
    'Arequipa, Peru',
    'Arusha, Tanzania',
    'Asheville, United States',
    'Ashgabat, Turkmenistan',
    'Asmara, Eritrea',
    'Astana, Kazakhstan',
    'Asuncion, Paraguay',
    'Athens, Greece',
    'Atlanta, United States',
    'Auckland, New Zealand',
    'Austin, United States',
    'Avignon, France',
    'Bacolod, Philippines',
    'Baguio, Philippines',
    'Baku, Azerbaijan',
    'Baltimore, United States',
    'Bamako, Mali',
    'Bandar Seri Begawan, Brunei',
    'Bandung, Indonesia',
    'Bangkok, Thailand',
    'Barcelona, Spain',
    'Bari, Italy',
    'Barranquilla, Colombia',
    'Basel, Switzerland',
    'Basra, Iraq',
    'Bath, United Kingdom',
    'Baton Rouge, United States',
    'Beijing, China',
    'Beirut, Lebanon',
    'Belem, Brazil',
    'Belfast, United Kingdom',
    'Belgrade, Serbia',
    'Belize City, Belize',
    'Belo Horizonte, Brazil',
    'Bend, United States',
    'Bengaluru, India',
    'Bergamo, Italy',
    'Bergen, Norway',
    'Berkeley, United States',
    'Berlin, Germany',
    'Bern, Switzerland',
    'Biarritz, France',
    'Bilbao, Spain',
    'Birmingham, United Kingdom',
    'Birmingham, United States',
    'Bishkek, Kyrgyzstan',
    'Bogota, Colombia',
    'Bologna, Italy',
    'Bordeaux, France',
    'Boston, United States',
    'Braga, Portugal',
    'Brasilia, Brazil',
    'Bratislava, Slovakia',
    'Brazzaville, Republic of the Congo',
    'Bremen, Germany',
    'Bridgetown, Barbados',
    'Brighton, United Kingdom',
    'Brisbane, Australia',
    'Bristol, United Kingdom',
    'Brno, Czechia',
    'Bruges, Belgium',
    'Brussels, Belgium',
    'Bucharest, Romania',
    'Budapest, Hungary',
    'Buenos Aires, Argentina',
    'Buffalo, United States',
    'Busan, South Korea',
    'Byron Bay, Australia',
    'Cadiz, Spain',
    'Cairns, Australia',
    'Cairo, Egypt',
    'Calgary, Canada',
    'Cali, Colombia',
    'Cambridge, United Kingdom',
    'Can Tho, Vietnam',
    'Canberra, Australia',
    'Cancun, Mexico',
    'Cape Town, South Africa',
    'Caracas, Venezuela',
    'Cardiff, United Kingdom',
    'Cartagena, Colombia',
    'Casablanca, Morocco',
    'Catania, Italy',
    'Cebu City, Philippines',
    'Chandigarh, India',
    'Changsha, China',
    'Chania, Greece',
    'Charleston, United States',
    'Charlotte, United States',
    'Chattanooga, United States',
    'Chengdu, China',
    'Chennai, India',
    'Chiang Mai, Thailand',
    'Chiang Rai, Thailand',
    'Chicago, United States',
    'Chisinau, Moldova',
    'Chittagong, Bangladesh',
    'Chongqing, China',
    'Christchurch, New Zealand',
    'Cincinnati, United States',
    'Cleveland, United States',
    'Cluj-Napoca, Romania',
    'Coimbra, Portugal',
    'Cologne, Germany',
    'Colombo, Sri Lanka',
    'Columbus, United States',
    'Conakry, Guinea',
    'Copenhagen, Denmark',
    'Cordoba, Argentina',
    'Cordoba, Spain',
    'Cork, Ireland',
    'Cotonou, Benin',
    'Cuenca, Ecuador',
    'Culiacan, Mexico',
    'Curitiba, Brazil',
    'Cusco, Peru',
    'Da Nang, Vietnam',
    'Daegu, South Korea',
    'Daejeon, South Korea',
    'Dakar, Senegal',
    'Dalian, China',
    'Dallas, United States',
    'Damascus, Syria',
    'Dar es Salaam, Tanzania',
    'Darwin, Australia',
    'Davao City, Philippines',
    'Denpasar, Indonesia',
    'Denver, United States',
    'Detroit, United States',
    'Dhaka, Bangladesh',
    'Dijon, France',
    'Dili, Timor-Leste',
    'Djibouti City, Djibouti',
    'Doha, Qatar',
    'Douala, Cameroon',
    'Dresden, Germany',
    'Dubai',
    'Dublin, Ireland',
    'Dubrovnik, Croatia',
    'Dunedin, New Zealand',
    'Durban, South Africa',
    'Dushanbe, Tajikistan',
    'Dusseldorf, Germany',
    'Edinburgh, United Kingdom',
    'Edmonton, Canada',
    'Ensenada, Mexico',
    'Erbil, Iraq',
    'Essaouira, Morocco',
    'Faro, Portugal',
    'Fez, Morocco',
    'Florence, Italy',
    'Florianopolis, Brazil',
    'Fort Lauderdale, United States',
    'Fort Worth, United States',
    'Fortaleza, Brazil',
    'Frankfurt, Germany',
    'Freetown, Sierra Leone',
    'Freiburg im Breisgau, Germany',
    'Fremantle, Australia',
    'Fresno, United States',
    'Fukuoka, Japan',
    'Funchal, Portugal',
    'Gaborone, Botswana',
    'Galle, Sri Lanka',
    'Galway, Ireland',
    'Gdansk, Poland',
    'Geneva, Switzerland',
    'Genoa, Italy',
    'George Town, Malaysia',
    'Georgetown, Guyana',
    'Ghent, Belgium',
    'Girona, Spain',
    'Glasgow, United Kingdom',
    'Gold Coast, Australia',
    'Gothenburg, Sweden',
    'Guadalajara, Mexico',
    'Guangzhou, China',
    'Guatemala City, Guatemala',
    'Guayaquil, Ecuador',
    'Guilin, China',
    'Guwahati, India',
    'Gwangju, South Korea',
    'Haifa, Israel',
    'Haiphong, Vietnam',
    'Hakodate, Japan',
    'Halifax, Canada',
    'Hamburg, Germany',
    'Hamilton, Canada',
    'Hangzhou, China',
    'Harare, Zimbabwe',
    'Harbin, China',
    'Hat Yai, Thailand',
    'Havana, Cuba',
    'Heidelberg, Germany',
    'Helsinki, Finland',
    'Heraklion, Greece',
    'Hiroshima, Japan',
    'Ho Chi Minh City, Vietnam',
    'Hobart, Australia',
    'Hoi An, Vietnam',
    'Hong Kong',
    'Honolulu, United States',
    'Houston, United States',
    'Hualien, Taiwan',
    'Hue, Vietnam',
    'Hyderabad, India',
    'Ibadan, Nigeria',
    'Ibiza Town, Spain',
    'Iloilo City, Philippines',
    'Incheon, South Korea',
    'Indore, India',
    'Innsbruck, Austria',
    'Ipoh, Malaysia',
    'Isfahan, Iran',
    'Islamabad, Pakistan',
    'Istanbul, Turkey',
    'Izmir, Turkey',
    'Jacksonville, United States',
    'Jaipur, India',
    'Jakarta, Indonesia',
    'Jeddah, Saudi Arabia',
    'Jeju City, South Korea',
    'Jeonju, South Korea',
    'Jerusalem, Israel',
    'Jodhpur, India',
    'Johannesburg, South Africa',
    'Johor Bahru, Malaysia',
    'Kabul, Afghanistan',
    'Kagoshima, Japan',
    'Kampala, Uganda',
    'Kanazawa, Japan',
    'Kandy, Sri Lanka',
    'Kansas City, United States',
    'Kaohsiung, Taiwan',
    'Karachi, Pakistan',
    'Kathmandu, Nepal',
    'Kelowna, Canada',
    'Key West, United States',
    'Kigali, Rwanda',
    'Kingston, Jamaica',
    'Kinshasa, Democratic Republic of the Congo',
    'Kobe, Japan',
    'Kochi, India',
    'Kolkata, India',
    'Kota Kinabalu, Malaysia',
    'Kozhikode, India',
    'Krakow, Poland',
    'Kuala Lumpur, Malaysia',
    'Kuching, Malaysia',
    'Kumamoto, Japan',
    'Kumasi, Ghana',
    'Kunming, China',
    'Kuwait City, Kuwait',
    'Kyiv, Ukraine',
    'Kyoto, Japan',
    'La Paz, Bolivia',
    'La Rochelle, France',
    'Lagos, Nigeria',
    'Lahore, Pakistan',
    'Las Palmas de Gran Canaria, Spain',
    'Las Vegas, United States',
    'Lausanne, Switzerland',
    'Lecce, Italy',
    'Leeds, United Kingdom',
    'Leipzig, Germany',
    'Leon, Mexico',
    'Libreville, Gabon',
    'Liege, Belgium',
    'Lille, France',
    'Lilongwe, Malawi',
    'Lima, Peru',
    'Limassol, Cyprus',
    'Limerick, Ireland',
    'Lisbon, Portugal',
    'Liverpool, United Kingdom',
    'Ljubljana, Slovenia',
    'Lome, Togo',
    'London, United Kingdom',
    'Long Beach, United States',
    'Los Angeles, United States',
    'Louisville, United States',
    'Luang Prabang, Laos',
    'Lucerne, Switzerland',
    'Lucknow, India',
    'Lugano, Switzerland',
    'Lusaka, Zambia',
    'Luxor, Egypt',
    'Lviv, Ukraine',
    'Lyon, France',
    'Maastricht, Netherlands',
    'Macau',
    'Madison, United States',
    'Madrid, Spain',
    'Makassar, Indonesia',
    'Malacca City, Malaysia',
    'Male, Maldives',
    'Malmo, Sweden',
    'Managua, Nicaragua',
    'Manama, Bahrain',
    'Manaus, Brazil',
    'Manchester, United Kingdom',
    'Mandalay, Myanmar',
    'Manila, Philippines',
    'Maputo, Mozambique',
    'Maracaibo, Venezuela',
    'Marbella, Spain',
    'Marrakech, Morocco',
    'Marseille, France',
    'Maseru, Lesotho',
    'Mashhad, Iran',
    'Matsuyama, Japan',
    'Mazatlan, Mexico',
    'Medan, Indonesia',
    'Medellin, Colombia',
    'Melbourne, Australia',
    'Memphis, United States',
    'Mendoza, Argentina',
    'Merida, Mexico',
    'Mexico City, Mexico',
    'Miami, United States',
    'Milan, Italy',
    'Milwaukee, United States',
    'Minneapolis, United States',
    'Minsk, Belarus',
    'Mombasa, Kenya',
    'Monaco',
    'Monrovia, Liberia',
    'Monterrey, Mexico',
    'Montevideo, Uruguay',
    'Montpellier, France',
    'Montreal, Canada',
    'Morelia, Mexico',
    'Moscow, Russia',
    'Mostar, Bosnia and Herzegovina',
    'Mumbai, India',
    'Munich, Germany',
    'Muscat, Oman',
    'Mysuru, India',
    'Nadi, Fiji',
    'Nagasaki, Japan',
    'Nagoya, Japan',
    'Naha, Japan',
    'Nairobi, Kenya',
    'Nanjing, China',
    'Nantes, France',
    'Naples, Italy',
    'Nashville, United States',
    'Nassau, Bahamas',
    'Natal, Brazil',
    'New Haven, United States',
    'New Orleans, United States',
    'New York, United States',
    'Newcastle upon Tyne, United Kingdom',
    'Newcastle, Australia',
    'Niamey, Niger',
    'Nice, France',
    'Nicosia, Cyprus',
    'Niigata, Japan',
    'Nimes, France',
    'Ningbo, China',
    'Nouakchott, Mauritania',
    'Noumea, New Caledonia',
    'Nuremberg, Germany',
    'Oaxaca City, Mexico',
    'Odense, Denmark',
    'Odesa, Ukraine',
    'Oran, Algeria',
    'Oranjestad, Aruba',
    'Orlando, United States',
    'Osaka, Japan',
    'Oslo, Norway',
    'Ottawa, Canada',
    'Ouagadougou, Burkina Faso',
    'Oxford, United Kingdom',
    'Palermo, Italy',
    'Palm Springs, United States',
    'Palma de Mallorca, Spain',
    'Panaji, India',
    'Panama City, Panama',
    'Papeete, French Polynesia',
    'Paramaribo, Suriname',
    'Paris, France',
    'Parma, Italy',
    'Perth, Australia',
    'Peshawar, Pakistan',
    'Philadelphia, United States',
    'Phnom Penh, Cambodia',
    'Phoenix, United States',
    'Phuket, Thailand',
    'Pisa, Italy',
    'Pittsburgh, United States',
    'Playa del Carmen, Mexico',
    'Plovdiv, Bulgaria',
    'Podgorica, Montenegro',
    'Pokhara, Nepal',
    'Port Harcourt, Nigeria',
    'Port Louis, Mauritius',
    'Port Moresby, Papua New Guinea',
    'Port of Spain, Trinidad and Tobago',
    'Portland, United States',
    'Porto Alegre, Brazil',
    'Porto, Portugal',
    'Poznan, Poland',
    'Prague, Czechia',
    'Praia, Cape Verde',
    'Pretoria, South Africa',
    'Providence, United States',
    'Puebla, Mexico',
    'Puerto Vallarta, Mexico',
    'Pune, India',
    'Punta del Este, Uruguay',
    'Qingdao, China',
    'Quebec City, Canada',
    'Queenstown, New Zealand',
    'Queretaro, Mexico',
    'Quito, Ecuador',
    'Rabat, Morocco',
    'Raleigh, United States',
    'Ramallah, Palestine',
    'Recife, Brazil',
    'Regina, Canada',
    'Reims, France',
    'Rennes, France',
    'Reykjavik, Iceland',
    'Richmond, United States',
    'Riga, Latvia',
    'Rio de Janeiro, Brazil',
    'Riyadh, Saudi Arabia',
    'Rochester, United States',
    'Rome, Italy',
    'Rosario, Argentina',
    'Rotorua, New Zealand',
    'Rotterdam, Netherlands',
    'Rouen, France',
    'Rovinj, Croatia',
    'Sacramento, United States',
    'Saint George\'s, Grenada',
    'Saint John\'s, Canada',
    'Saint Louis, United States',
    'Saint Petersburg, Russia',
    'Salt Lake City, United States',
    'Salta, Argentina',
    'Salvador, Brazil',
    'Salzburg, Austria',
    'Samarkand, Uzbekistan',
    'San Antonio, United States',
    'San Diego, United States',
    'San Francisco, United States',
    'San Jose, Costa Rica',
    'San Jose, United States',
    'San Juan, Puerto Rico',
    'San Miguel de Allende, Mexico',
    'San Salvador, El Salvador',
    'San Sebastian, Spain',
    'Santa Barbara, United States',
    'Santa Cruz de la Sierra, Bolivia',
    'Santa Fe, United States',
    'Santiago de Compostela, Spain',
    'Santiago, Chile',
    'Santo Domingo, Dominican Republic',
    'Sao Paulo, Brazil',
    'Sapporo, Japan',
    'Sarajevo, Bosnia and Herzegovina',
    'Saskatoon, Canada',
    'Savannah, United States',
    'Seattle, United States',
    'Semarang, Indonesia',
    'Sendai, Japan',
    'Seoul, South Korea',
    'Seville, Spain',
    'Sfax, Tunisia',
    'Shanghai, China',
    'Shantou, China',
    'Sharjah, United Arab Emirates',
    'Sheffield, United Kingdom',
    'Shenzhen, China',
    'Shiraz, Iran',
    'Sibiu, Romania',
    'Siem Reap, Cambodia',
    'Siena, Italy',
    'Singapore',
    'Skopje, North Macedonia',
    'Sofia, Bulgaria',
    'Sonoma, United States',
    'Split, Croatia',
    'Stavanger, Norway',
    'Stockholm, Sweden',
    'Strasbourg, France',
    'Stuttgart, Germany',
    'Sucre, Bolivia',
    'Surabaya, Indonesia',
    'Surat, India',
    'Suva, Fiji',
    'Suwon, South Korea',
    'Suzhou, China',
    'Swansea, United Kingdom',
    'Sydney, Australia',
    'Syracuse, United States',
    'Taichung, Taiwan',
    'Tainan, Taiwan',
    'Taipei, Taiwan',
    'Takamatsu, Japan',
    'Tallinn, Estonia',
    'Tampa, United States',
    'Tampere, Finland',
    'Tangier, Morocco',
    'Tashkent, Uzbekistan',
    'Tbilisi, Georgia',
    'Tegucigalpa, Honduras',
    'Tehran, Iran',
    'Tel Aviv, Israel',
    'The Hague, Netherlands',
    'Thessaloniki, Greece',
    'Thimphu, Bhutan',
    'Thiruvananthapuram, India',
    'Tianjin, China',
    'Tijuana, Mexico',
    'Timisoara, Romania',
    'Tirana, Albania',
    'Tokyo, Japan',
    'Toronto, Canada',
    'Toulouse, France',
    'Tours, France',
    'Tripoli, Libya',
    'Trondheim, Norway',
    'Tucson, United States',
    'Tulsa, United States',
    'Tunis, Tunisia',
    'Turin, Italy',
    'Turku, Finland',
    'Ubud, Indonesia',
    'Udaipur, India',
    'Ulaanbaatar, Mongolia',
    'Uppsala, Sweden',
    'Utrecht, Netherlands',
    'Valencia, Spain',
    'Valletta, Malta',
    'Valparaiso, Chile',
    'Vancouver, Canada',
    'Varanasi, India',
    'Venice, Italy',
    'Veracruz, Mexico',
    'Verona, Italy',
    'Victoria, Canada',
    'Victoria, Seychelles',
    'Vienna, Austria',
    'Vientiane, Laos',
    'Vilnius, Lithuania',
    'Warsaw, Poland',
    'Washington, United States',
    'Wellington, New Zealand',
    'West Palm Beach, United States',
    'Willemstad, Curacao',
    'Windhoek, Namibia',
    'Winnipeg, Canada',
    'Wroclaw, Poland',
    'Wuhan, China',
    'Wuxi, China',
    'Xi\'an, China',
    'Xiamen, China',
    'Yangon, Myanmar',
    'Yaounde, Cameroon',
    'Yerevan, Armenia',
    'Yogyakarta, Indonesia',
    'Yokohama, Japan',
    'Zagreb, Croatia',
    'Zanzibar City, Tanzania',
    'Zaragoza, Spain',
    'Zurich, Switzerland',
] as const;
