const { injectPreInstall } = jest.requireActual<{
    injectPreInstall: (podfileContents: string) => string;
}>('../withMapsStaticPods');

const PODFILE = [
    "target 'Napkin' do",
    '  use_react_native!',
    '',
    '  post_install do |installer|',
    '    react_native_post_install(installer)',
    '  end',
    'end',
    '',
].join('\n');

const PRE_INSTALL_BLOCK = [
    '  # @generated by withMapsStaticPods',
    '  pre_install do |installer|',
    '    installer.pod_targets.each do |pod|',
    "      if ['react-native-maps', 'react-native-google-maps'].include?(pod.name)",
    '        def pod.build_type',
    '          Pod::BuildType.static_library',
    '        end',
    '      end',
    '    end',
    '  end',
].join('\n');

describe('injectPreInstall', () => {
    it('injects the maps static-library hook once before post_install', () => {
        const injected = injectPreInstall(PODFILE);

        expect(injected).toBe(
            PODFILE.replace(
                '  post_install do |installer|',
                `${PRE_INSTALL_BLOCK}\n\n  post_install do |installer|`,
            ),
        );
        expect(injected.match(/# @generated by withMapsStaticPods/g)).toHaveLength(1);
    });

    it('is idempotent when the marker is already present', () => {
        const injected = injectPreInstall(PODFILE);

        expect(injectPreInstall(injected)).toBe(injected);
    });

    it('throws when the post_install anchor is missing', () => {
        expect(() => injectPreInstall("target 'Napkin' do\nend\n")).toThrow(
            'withMapsStaticPods: Podfile is missing the `post_install do |installer|` anchor.',
        );
    });
});
