const fs = require('node:fs/promises');
const path = require('node:path');
const { withDangerousMod } = require('expo/config-plugins');

const MARKER = '# @generated by withMapsStaticPods';
const PRE_INSTALL_LINES = [
    MARKER,
    'pre_install do |installer|',
    '  installer.pod_targets.each do |pod|',
    "    if ['react-native-maps', 'react-native-google-maps'].include?(pod.name)",
    '      def pod.build_type',
    '        Pod::BuildType.static_library',
    '      end',
    '    end',
    '  end',
    'end',
];
const POST_INSTALL_ANCHOR = /^([ \t]*)post_install do \|installer\|[ \t]*$/m;

function injectPreInstall(podfileContents) {
    if (podfileContents.includes(MARKER)) return podfileContents;

    const anchor = podfileContents.match(POST_INSTALL_ANCHOR);
    if (!anchor) {
        throw new Error(
            'withMapsStaticPods: Podfile is missing the `post_install do |installer|` anchor.',
        );
    }

    const indentation = anchor[1];
    const preInstall = PRE_INSTALL_LINES.map((line) => `${indentation}${line}`).join('\n');
    return podfileContents.replace(POST_INSTALL_ANCHOR, `${preInstall}\n\n${anchor[0]}`);
}

function withMapsStaticPods(config) {
    return withDangerousMod(config, [
        'ios',
        async (modConfig) => {
            const podfilePath = path.join(modConfig.modRequest.platformProjectRoot, 'Podfile');
            const podfileContents = await fs.readFile(podfilePath, 'utf8');
            const updatedContents = injectPreInstall(podfileContents);

            if (updatedContents !== podfileContents) {
                await fs.writeFile(podfilePath, updatedContents, 'utf8');
            }
            return modConfig;
        },
    ]);
}

module.exports = withMapsStaticPods;
module.exports.injectPreInstall = injectPreInstall;
